### ISSUE TITLE
The console throws an error when clicking on deposit

### ISSUE THREAD

**Issue by EVA123123** [TownyAdvanced/TownyMenus#53]
[Server thread/ERROR]: Could not pass event InventoryClickEvent to TownyMenus v0.0.9
java.lang.ExceptionInInitializerError: null
	at T【城镇菜单】TownyMenus-0.0.9.jar/io.github.townyadvanced.townymenus.libs.anvilgui.AnvilGUI$Builder.<init>(AnvilGUI.java:401) ~[T【城镇菜单】TownyMenus-0.0.9.jar:?]
	at T【城镇菜单】TownyMenus-0.0.9.jar/io.github.townyadvanced.townymenus.gui.action.UserInputAction.onClick(UserInputAction.java:28) ~[T【城镇菜单】TownyMenus-0.0.9.jar:?]
	at T【城镇菜单】TownyMenus-0.0.9.jar/io.github.townyadvanced.townymenus.listeners.InventoryListener.lambda$onInventoryClick$0(InventoryListener.java:37) ~[T【城镇菜单】TownyMenus-0.0.9.jar:?]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at T【城镇菜单】TownyMenus-0.0.9.jar/io.github.townyadvanced.townymenus.listeners.InventoryListener.onInventoryClick(InventoryListener.java:37) ~[T【城镇菜单】TownyMenus-0.0.9.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor331.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-2230-eac4198]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3260) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1546) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1523) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1446) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1412) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1273) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.6.jar:1.20.6-2230-eac4198]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at T【城镇菜单】TownyMenus-0.0.9.jar/io.github.townyadvanced.townymenus.libs.anvilgui.version.VersionMatcher.match(VersionMatcher.java:25) ~[T【城镇菜单】TownyMenus-0.0.9.jar:?]
	at T【城镇菜单】TownyMenus-0.0.9.jar/io.github.townyadvanced.townymenus.libs.anvilgui.AnvilGUI.<clinit>(AnvilGUI.java:43) ~[T【城镇菜单】TownyMenus-0.0.9.jar:?]
	... 29 more

purpur-1.20.6
towny-0.100.3.0
TownyMenus-0.0.9

**Comment by Warriorrrr** [comment]
Fixed in 0.0.11
